server:
  port: 8082

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nexushr
    username: postgres
    password: Mp@762003
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false

jwt:
  secret: change-this-to-a-long-random-secret-in-prod
  expiration-ms: 900000
  refresh-expiration-ms: 604800000