server:
  port: 8083

spring:
  application:
    name: payroll-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nexushr
    username: postgres
    password: Mp@762003
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect